# Generated by Django 5.0.3 on 2024-03-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('head', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America'), ('CA', 'Central America')], default='AF', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('SUV', 'Sport Utility Vehicle'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck')], default='Sedan', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=450)),
                ('value', models.IntegerField()),
                ('manufacture_date', models.DateField(default='1970-01-01')),
                ('predecessor', models.CharField(default='', max_length=100)),
                ('successor', models.CharField(default='', max_length=100)),
                ('engine', models.IntegerField(default=None, null=True)),
                ('image_url', models.URLField(default='https://www.vistacars.in/assets/product_images/default.png')),
                ('colors', models.ManyToManyField(to='main_app.color')),
                ('make', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.make')),
            ],
        ),
    ]
