# Generated by Django 5.0.3 on 2024-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car_engine_car_manufacture_date_car_predecessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(default='https://www.vistacars.in/assets/product_images/default.png'),
        ),
    ]
