# Generated by Django 5.0.3 on 2024-03-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Sports Car', 'Sports Car'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('SUV', 'Sport Utility Vehicle'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck')], default='Sedan', max_length=20),
        ),
    ]
